import { NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/db';
import StudyMaterial from '@/lib/models/StudyMaterial';

// GET /api/materials - Get all study materials (optional filtering by branch/semester)
export async function GET(request: Request) {
  try {
    const { searchParams } = new URL(request.url);
    const branch = searchParams.get('branch');
    const semester = searchParams.get('semester');

    await connectToDatabase();

    const allowedSubjects = [
      'Elements of Mechanical Engineering',
      'Engineering Physics',
      'Environmental Studies',
      'English Language Lab',
      'Engineering & Applied Physics Laboratory',
      'Workshop Practice',
      'Basic English and Communication Skills',
      'Engineering Mechanics',
      'Mathematics I',
      'Engineering Drawing',
      'Basic Electrical Engineering',
      'Computer Programming',
      'Engineering Chemistry',
      'Chemistry Laboratory',
      'Computer Programming Laboratory',
      'Fundamental Knowledge of Accreditation',
      'Advanced English Communication Skills',
      'Mathematics II',
      // Semester 3 Mechanical Engineering subjects
      'Mechanics of Materials-I',
      'Fundamentals of Dynamics',
      'Manufacturing Processes-I',
      'Engineering Thermodynamics',
      'Fluid Mechanics-I',
      'Society and Sensitivity',
      'Manufacturing Processes-I Lab',
      'Fluid Mechanics Lab',
      'Machine Drawing & Solid Modeling Lab',
      // Semester 4 Mechanical Engineering subjects
      'Mechanics of Materials-II',
      'Theory of Machines-I',
      'Manufacturing Processes-II',
      'Heat Transfer',
      'Applied Thermodynamics-I',
      'Mathematics-III',
      'Mechanics of Materials Lab',
      'Theory of Machines-I Lab',
      'Manufacturing Processes-II Lab',
      'Heat Transfer Lab',
      // Semester 5 Mechanical Engineering subjects
      'Machine Design-I',
      'Theory of Machines-II',
      'Material Science and Engineering',
      'Applied Thermodynamics-II',
      'Industrial Engineering-I',
      'Introduction to Mechatronics',
      'Introduction to Electric Vehicle',
      'Theory of Machines-II Lab',
      'Thermal Engineering Lab',
      'Research Lab',
      // Semester 6 Mechanical Engineering subjects
      'Machine Design-II',
      'Fluid Mechanics-II',
      'Industrial Engineering-II',
      'Mathematics-IV',
      'Elective-I',
      'Basic Robot Mechanics',
      'Sustainable Engineering',
      'Industrial Engineering Lab',
      'Industrial Training',
      'Seminar',
      // Semester 7 Mechanical Engineering subjects
      'Measurement and Instrumentation',
      'Engineering Economics',
      'Elective-II',
      'Elective-III',
      'Elective-IV',
      'Simulation Lab',
      'Pre Project',
      // Semester 3 Chemical Engineering subjects
      'Chemical Process Calculations',
      'Process Fluid Mechanics',
      'Mechanical Operations',
      'Process Instrumentation',
      'Chemical Engineering Thermodynamics-I',
      'Engineering Ethics',
      'Numerical Methods',
      'Mechanical Operations Laboratory',
      // Semester 4 Chemical Engineering subjects
      'Chemical Reaction Engineering-I',
      'Chemical Engineering Thermodynamics-II',
      'Heat Transfer',
      'Chemical Process Technology',
      'Chemical Engineering Mathematics',
      'Engineering Economics and Management',
      'Energy Technology Laboratory',
      'Fluid Mechanics Laboratory',
      // Semester 5 Chemical Engineering subjects
      'Process Equipment Design-I',
      'Chemical Reaction Engineering-II',
      'Mass Transfer-I',
      'Biochemical Engineering',
      'Elective-I',
      'Institute Open Elective-I',
      'Heat Transfer Laboratory',
      'Computer Simulation Laboratory',
      'Applied Mathematics for Chemical Engineers',
      // Semester 6 Chemical Engineering subjects
      'Process Equipment Design-II',
      'Chemical Process Safety',
      'Process Dynamics and Control',
      'Mass Transfer-II',
      'Elective-II',
      'Institute Open Elective-II',
      'Chemical Reaction Engineering Laboratory',
      'Mass Transfer Laboratory',
      'Industrial/Research Training and Presentation',
      'Seminar',
      'Membrane Science and Engineering',
      // Semester 7 Chemical Engineering subjects
      'Pre-project work',
      'Transport Phenomena',
      'Process Economics and Plant Design',
      'Elective-III',
      'Elective-IV',
      'Elective-V',
      'Process Dynamics and Control Laboratory',
      // Semester 3 ECE subjects
      'Electronics-I',
      'Network Analysis',
      'Signals and Systems',
      'Electronic Engineering Materials',
      'Philosophy for Engineers: Society, Culture and Ethics',
      'Mathematics III',
      'Electronics-I Lab',
      'Circuit Analysis Lab',
      'Signals & Systems Lab',
      // Semester 4 ECE subjects
      'Electronics-II',
      'Digital Elect. & Logic Design',
      'Communication-I',
      'Applied EMF & Waves',
      'Control Systems',
      'Mathematics IV',
      'Electronics-II Lab',
      'DELD Lab',
      'Communication-I Lab',
      // Semester 5 ECE subjects
      'Microprocessor',
      'Electronic Devices',
      'Communication-II',
      'Antenna and Wave Propagation',
      'Mathematics-V',
      'Institute Elective I',
      'Microprocessor Lab',
      'Communication-II Lab',
      // Semester 6 ECE subjects
      'Digital Signal Processing',
      'VLSI Design',
      'Computer Organization & Architecture',
      'Data Communication',
      'Elective II',
      'Institute Elective-II',
      'VLSI Design Lab',
      'Digital Signal Processing Lab',
      'Industrial Training',
      // Semester 7 ECE subjects
      'Microwave Engineering',
      'Wireless Communication',
      'Electronic M&I',
      'Industrial Organization & Management',
      'Project pre-work',
      'Elective IV',
      'Microwave Engineering Lab',
      'EDA Tools I',
      // Semester 3 Metallurgy subjects
      'Electronic, Magnetic and Di-electric Materials',
      'Thermodynamics of Materials',
      'Physical Metallurgy',
      'Mineral Dressing & Principles of Extractive Metallurgy',
      'Probability and Statistics',
      'Entrepreneurship Development',
      'Laboratory Practice in Physical Metallurgy',
      'Laboratory Practice in Mineral Dressing & Principles of Extractive Metallurgy',
      // Semester 4 Metallurgy subjects
      'Phase Transformation and Heat Treatment of Metals',
      'Kinetics of Metallurgical Processes',
      'Non-Ferrous Metal Extraction',
      'Joining of Materials',
      'Numerical Methods',
      'Engineering Economics and Management',
      'Laboratory Practice in Heat Treatment',
      'Laboratory Practice in Joining of Materials',
      // Semester 5 Metallurgy subjects
      'Corrosion Engineering',
      'Iron Making',
      'Mechanical Behaviour of Materials',
      'Materials Characterisation',
      'Professional Elective - I',
      'Institute Open Elective - I',
      'Laboratory Practice in Corrosion Engineering',
      'Laboratory Practice in Mechanical Behaviour of Materials',
      'Laboratory Practice in Materials Characterisation',
      'Honours Elective - I',
      // Semester 6 Metallurgy subjects
      'Ceramic Technology',
      'Steel Making',
      'Powder Metallurgy',
      'Mechanical Working of Materials',
      'Professional Elective - II',
      'Institute Open Elective - II',
      'Laboratory Practice in Ceramic Technology',
      'Laboratory Practice in Mechanical Working of Materials',
      'Industrial Training/Internship',
      'Honours Elective - II',
      // Semester 7 Metallurgy subjects
      'Metal Casting',
      'Polymer Technology',
      'Professional Elective - III',
      'Professional Elective - IV',
      'Professional Elective - V',
      'Laboratory Practice in Metal Casting',
      'Laboratory Practice in Polymer Technology',
      'Project Preliminary Work',
      'Honours Elective - III',
      'Honours Elective - IV',
      // Semester 3 CSE subjects
      'Object Oriented Programming',
      'Database Management Systems',
      'Software Engineering',
      'Electronic Devices and Circuits',
      'Discrete Mathematics',
      'Entrepreneurship Development',
      'Object Oriented Programming-Lab',
      'Database Management System Lab',
      // Semester 4 CSE subjects
      'Data Structures',
      'Internet & Web Technologies',
      'Theory of Computation',
      'Digital Electronics & Logic Design',
      'Probability & Statistics',
      'Project Management',
      'Data Structures-Lab',
      'Digital Electronics & Logic Design Lab',
      // Semester 5 CSE subjects
      'Design & Analysis of Algorithms',
      'Microprocessor',
      'Operating Systems',
      'Python Programming',
      'Open Elective-I',
      'Communication Systems',
      'Microprocessor-Lab',
      'Python Programming-Lab',
      // Semester 6 CSE subjects
      'Artificial Intelligence',
      'Computer Networks',
      'Computer Organization & Architecture',
      'Java Programming',
      'Open Elective-II',
      'Elective-I',
      'Artificial Intelligence-Lab',
      'Computer Networks-Lab',
      // Semester 7 CSE subjects
      'Network Security',
      'Compiler Design',
      'Elective-II',
      'Elective-III',
      'Elective-IV',
      'Network Security-Lab',
      'Pre-Project',
      // Semester 3 IT subjects
      'Control System',
      'Logic and Graphic Theory',
      'Data Structures Lab',
      'Object-Oriented Programming Lab',
      'Electronics Devices and Circuits Lab',
      'Web Programming',
      // Semester 4 IT subjects
      'Digital Electronics and Logic Design',
      'Database Management System',
      'Introduction to Probability and Statistics',
      'Signal and Systems',
      'Digital Electronics and Logic Design Lab',
      'Operating System Lab',
      'Database Management System Lab',
      // Semester 5 IT subjects
      'Design and Analysis of Algorithms',
      'Elective I',
      'Institute Open Elective I',
      'Design & Analysis of Algorithms Lab',
      'Artificial Intelligence Lab',
      // Semester 6 IT subjects
      'Machine Learning',
      'Big Data',
      'Institute Open Elective II',
      'Computer Networks Lab',
      'Machine Learning Lab',
      'Industrial Training and Internship',
      'Elective III',
      // Semester 7 IT subjects
      'Image Processing',
      'Image Processing Lab',
      'Elective VII',
      // Semester 3 Civil subjects
      'Structural Analysis-I',
      'Structural Analysis Lab',
      'Fluid Mechanics',
      'Fluid Mechanics Lab-I',
      'Surveying-I',
      'Surveying Lab-I',
      'Building Materials and Construction',
      'Basics of Industrial Economics and Management',
      // Semester 4 Civil subjects
      'Structural Analysis-II',
      'Fluid Flow in Pipes and Channels',
      'Fluid Mechanics Lab-II',
      'Surveying-II',
      'Surveying Lab-II',
      'Engineering Geology',
      'Geology Lab',
      'Civil Engineering Drawing',
      'Survey Camp',
      // Semester 5 Civil subjects
      'Design of Reinforced Concrete Structures-I',
      'Concrete Lab',
      'Highway Engineering',
      'Highway Engineering Lab',
      'Geotechnical Engineering-I',
      'Geotechnical Lab-I',
      'Water Resources Engineering',
      'Quantity Surveying and Cost Evaluation',
      'Philosophy for Engineers: Society, Culture and Ethics',
      'Honors Elective-I',
      'Quantity Surveying and Cost Evaluation (Institute Elective-I)',
      'Building Materials and Construction (Institute Elective-II)',
      // Semester 6 Civil subjects
      'Design of Steel Structures',
      'Traffic Engineering',
      'Traffic Engineering Lab.',
      'Geotechnical Engineering-II',
      'Geotechnical Lab-II',
      'Environmental Engineering-I',
      'Water Quality Lab',
      'Industrial Training and Presentation',
      'Honors Elective-II',
      'Environmental Engineering (Institute Elective-I)',
      'Civil Engineering Drawing (Institute Elective-II)',
      // Semester 7 Civil subjects
      'Pre-Project work',
      'Honours Elective-III',
      'Honours Elective-IV',
      'Honours Elective-V',
      // Semester 3 Electrical subjects
      'Electric Circuit Analysis',
      'Electric Machines I',
      'Electromagnetic Field & Waves',
      'Electric Circuit Analysis Lab',
      'Python Programming Lab',
      // Semester 4 Electrical subjects
      'Electrical Measurements and Instrumentation',
      'Electric Machines II',
      'Power Systems I',
      'Control Systems I',
      'Basic Management Principles',
      'Electric Machines Lab I',
      'Control Systems LAB',
      'Electrical Measurements and Instrumentation Lab',
      // Semester 5 Electrical subjects
      'Control Systems II',
      'Power Systems II',
      'Power Electronics',
      'Electric Machines III',
      'Program Elective I',
      'Institute Elective I',
      'Power Systems Lab I',
      'Power Electronics Lab',
      'Electric Machines Lab II',
      // Semester 6 Electrical subjects
      'Power Systems III',
      'Electric Drives',
      'Design of Electric Machines',
      'Microprocessors',
      'Program Elective II',
      'Program Elective III',
      'Power Systems Lab II',
      'Microprocessors Lab',
      'Industrial Training & Viva',
      // Semester 7 Electrical subjects
      'Power System Protection',
      'Program Elective IV',
      'Program Elective V',
      'Program Elective VI',
      'Program Elective VII',
      'Program Elective VIII',
      'Personal Financial Planning',
      'Power System Protection Lab',
      'Program Elective Lab I'
    ];

    // Purge materials that do not belong to the allowed subjects (ensuring absolute decorum)
    await StudyMaterial.deleteMany({
      subject: { $nin: allowedSubjects }
    });

    const query: any = {};
    if (branch && branch !== 'all') {
      query.branch = branch;
    }
    if (semester && semester !== 'all') {
      const semNum = parseInt(semester);
      if (!isNaN(semNum)) {
        query.semester = semNum;
      }
    }

    // Return materials sorted by newest first
    const materials = await StudyMaterial.find(query).sort({ createdAt: -1 });
    return NextResponse.json({ data: materials });
  } catch (error: any) {
    console.error('Failed to fetch materials:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}

// POST /api/materials - Create a new study material
export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { title, subject, description, branch, semester, type, fileUrl, author, uploaderId } = body;

    if (!title || !description || !branch || !semester || !type || !fileUrl || !author) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const allowedSubjects = [
      'Elements of Mechanical Engineering',
      'Engineering Physics',
      'Environmental Studies',
      'English Language Lab',
      'Engineering & Applied Physics Laboratory',
      'Workshop Practice',
      'Basic English and Communication Skills',
      'Engineering Mechanics',
      'Mathematics I',
      'Engineering Drawing',
      'Basic Electrical Engineering',
      'Computer Programming',
      'Engineering Chemistry',
      'Chemistry Laboratory',
      'Computer Programming Laboratory',
      'Fundamental Knowledge of Accreditation',
      'Advanced English Communication Skills',
      'Mathematics II',
      // Semester 3 Mechanical Engineering subjects
      'Mechanics of Materials-I',
      'Fundamentals of Dynamics',
      'Manufacturing Processes-I',
      'Engineering Thermodynamics',
      'Fluid Mechanics-I',
      'Society and Sensitivity',
      'Manufacturing Processes-I Lab',
      'Fluid Mechanics Lab',
      'Machine Drawing & Solid Modeling Lab',
      // Semester 4 Mechanical Engineering subjects
      'Mechanics of Materials-II',
      'Theory of Machines-I',
      'Manufacturing Processes-II',
      'Heat Transfer',
      'Applied Thermodynamics-I',
      'Mathematics-III',
      'Mechanics of Materials Lab',
      'Theory of Machines-I Lab',
      'Manufacturing Processes-II Lab',
      'Heat Transfer Lab',
      // Semester 5 Mechanical Engineering subjects
      'Machine Design-I',
      'Theory of Machines-II',
      'Material Science and Engineering',
      'Applied Thermodynamics-II',
      'Industrial Engineering-I',
      'Introduction to Mechatronics',
      'Introduction to Electric Vehicle',
      'Theory of Machines-II Lab',
      'Thermal Engineering Lab',
      'Research Lab',
      // Semester 6 Mechanical Engineering subjects
      'Machine Design-II',
      'Fluid Mechanics-II',
      'Industrial Engineering-II',
      'Mathematics-IV',
      'Elective-I',
      'Basic Robot Mechanics',
      'Sustainable Engineering',
      'Industrial Engineering Lab',
      'Industrial Training',
      'Seminar',
      // Semester 7 Mechanical Engineering subjects
      'Measurement and Instrumentation',
      'Engineering Economics',
      'Elective-II',
      'Elective-III',
      'Elective-IV',
      'Simulation Lab',
      'Pre Project',
      // Semester 3 Chemical Engineering subjects
      'Chemical Process Calculations',
      'Process Fluid Mechanics',
      'Mechanical Operations',
      'Process Instrumentation',
      'Chemical Engineering Thermodynamics-I',
      'Engineering Ethics',
      'Numerical Methods',
      'Mechanical Operations Laboratory',
      // Semester 4 Chemical Engineering subjects
      'Chemical Reaction Engineering-I',
      'Chemical Engineering Thermodynamics-II',
      'Heat Transfer',
      'Chemical Process Technology',
      'Chemical Engineering Mathematics',
      'Engineering Economics and Management',
      'Energy Technology Laboratory',
      'Fluid Mechanics Laboratory',
      // Semester 5 Chemical Engineering subjects
      'Process Equipment Design-I',
      'Chemical Reaction Engineering-II',
      'Mass Transfer-I',
      'Biochemical Engineering',
      'Elective-I',
      'Institute Open Elective-I',
      'Heat Transfer Laboratory',
      'Computer Simulation Laboratory',
      'Applied Mathematics for Chemical Engineers',
      // Semester 6 Chemical Engineering subjects
      'Process Equipment Design-II',
      'Chemical Process Safety',
      'Process Dynamics and Control',
      'Mass Transfer-II',
      'Elective-II',
      'Institute Open Elective-II',
      'Chemical Reaction Engineering Laboratory',
      'Mass Transfer Laboratory',
      'Industrial/Research Training and Presentation',
      'Seminar',
      'Membrane Science and Engineering',
      // Semester 7 Chemical Engineering subjects
      'Pre-project work',
      'Transport Phenomena',
      'Process Economics and Plant Design',
      'Elective-III',
      'Elective-IV',
      'Elective-V',
      'Process Dynamics and Control Laboratory',
      // Semester 3 ECE subjects
      'Electronics-I',
      'Network Analysis',
      'Signals and Systems',
      'Electronic Engineering Materials',
      'Philosophy for Engineers: Society, Culture and Ethics',
      'Mathematics III',
      'Electronics-I Lab',
      'Circuit Analysis Lab',
      'Signals & Systems Lab',
      // Semester 4 ECE subjects
      'Electronics-II',
      'Digital Elect. & Logic Design',
      'Communication-I',
      'Applied EMF & Waves',
      'Control Systems',
      'Mathematics IV',
      'Electronics-II Lab',
      'DELD Lab',
      'Communication-I Lab',
      // Semester 5 ECE subjects
      'Microprocessor',
      'Electronic Devices',
      'Communication-II',
      'Antenna and Wave Propagation',
      'Mathematics-V',
      'Institute Elective I',
      'Microprocessor Lab',
      'Communication-II Lab',
      // Semester 6 ECE subjects
      'Digital Signal Processing',
      'VLSI Design',
      'Computer Organization & Architecture',
      'Data Communication',
      'Elective II',
      'Institute Elective-II',
      'VLSI Design Lab',
      'Digital Signal Processing Lab',
      'Industrial Training',
      // Semester 7 ECE subjects
      'Microwave Engineering',
      'Wireless Communication',
      'Electronic M&I',
      'Industrial Organization & Management',
      'Project pre-work',
      'Elective IV',
      'Microwave Engineering Lab',
      'EDA Tools I',
      // Semester 3 Metallurgy subjects
      'Electronic, Magnetic and Di-electric Materials',
      'Thermodynamics of Materials',
      'Physical Metallurgy',
      'Mineral Dressing & Principles of Extractive Metallurgy',
      'Probability and Statistics',
      'Entrepreneurship Development',
      'Laboratory Practice in Physical Metallurgy',
      'Laboratory Practice in Mineral Dressing & Principles of Extractive Metallurgy',
      // Semester 4 Metallurgy subjects
      'Phase Transformation and Heat Treatment of Metals',
      'Kinetics of Metallurgical Processes',
      'Non-Ferrous Metal Extraction',
      'Joining of Materials',
      'Numerical Methods',
      'Engineering Economics and Management',
      'Laboratory Practice in Heat Treatment',
      'Laboratory Practice in Joining of Materials',
      // Semester 5 Metallurgy subjects
      'Corrosion Engineering',
      'Iron Making',
      'Mechanical Behaviour of Materials',
      'Materials Characterisation',
      'Professional Elective - I',
      'Institute Open Elective - I',
      'Laboratory Practice in Corrosion Engineering',
      'Laboratory Practice in Mechanical Behaviour of Materials',
      'Laboratory Practice in Materials Characterisation',
      'Honours Elective - I',
      // Semester 6 Metallurgy subjects
      'Ceramic Technology',
      'Steel Making',
      'Powder Metallurgy',
      'Mechanical Working of Materials',
      'Professional Elective - II',
      'Institute Open Elective - II',
      'Laboratory Practice in Ceramic Technology',
      'Laboratory Practice in Mechanical Working of Materials',
      'Industrial Training/Internship',
      'Honours Elective - II',
      // Semester 7 Metallurgy subjects
      'Metal Casting',
      'Polymer Technology',
      'Professional Elective - III',
      'Professional Elective - IV',
      'Professional Elective - V',
      'Laboratory Practice in Metal Casting',
      'Laboratory Practice in Polymer Technology',
      'Project Preliminary Work',
      'Honours Elective - III',
      'Honours Elective - IV',
      // Semester 3 CSE subjects
      'Object Oriented Programming',
      'Database Management Systems',
      'Software Engineering',
      'Electronic Devices and Circuits',
      'Discrete Mathematics',
      'Entrepreneurship Development',
      'Object Oriented Programming-Lab',
      'Database Management System Lab',
      // Semester 4 CSE subjects
      'Data Structures',
      'Internet & Web Technologies',
      'Theory of Computation',
      'Digital Electronics & Logic Design',
      'Probability & Statistics',
      'Project Management',
      'Data Structures-Lab',
      'Digital Electronics & Logic Design Lab',
      // Semester 5 CSE subjects
      'Design & Analysis of Algorithms',
      'Microprocessor',
      'Operating Systems',
      'Python Programming',
      'Open Elective-I',
      'Communication Systems',
      'Microprocessor-Lab',
      'Python Programming-Lab',
      // Semester 6 CSE subjects
      'Artificial Intelligence',
      'Computer Networks',
      'Computer Organization & Architecture',
      'Java Programming',
      'Open Elective-II',
      'Elective-I',
      'Artificial Intelligence-Lab',
      'Computer Networks-Lab',
      // Semester 7 CSE subjects
      'Network Security',
      'Compiler Design',
      'Elective-II',
      'Elective-III',
      'Elective-IV',
      'Network Security-Lab',
      'Pre-Project',
      // Semester 3 IT subjects
      'Control System',
      'Logic and Graphic Theory',
      'Data Structures Lab',
      'Object-Oriented Programming Lab',
      'Electronics Devices and Circuits Lab',
      'Web Programming',
      // Semester 4 IT subjects
      'Digital Electronics and Logic Design',
      'Database Management System',
      'Introduction to Probability and Statistics',
      'Signal and Systems',
      'Digital Electronics and Logic Design Lab',
      'Operating System Lab',
      'Database Management System Lab',
      // Semester 5 IT subjects
      'Design and Analysis of Algorithms',
      'Elective I',
      'Institute Open Elective I',
      'Design & Analysis of Algorithms Lab',
      'Artificial Intelligence Lab',
      // Semester 6 IT subjects
      'Machine Learning',
      'Big Data',
      'Institute Open Elective II',
      'Computer Networks Lab',
      'Machine Learning Lab',
      'Industrial Training and Internship',
      'Elective III',
      // Semester 7 IT subjects
      'Image Processing',
      'Image Processing Lab',
      'Elective VII',
      // Semester 3 Civil subjects
      'Structural Analysis-I',
      'Structural Analysis Lab',
      'Fluid Mechanics',
      'Fluid Mechanics Lab-I',
      'Surveying-I',
      'Surveying Lab-I',
      'Building Materials and Construction',
      'Basics of Industrial Economics and Management',
      // Semester 4 Civil subjects
      'Structural Analysis-II',
      'Fluid Flow in Pipes and Channels',
      'Fluid Mechanics Lab-II',
      'Surveying-II',
      'Surveying Lab-II',
      'Engineering Geology',
      'Geology Lab',
      'Civil Engineering Drawing',
      'Survey Camp',
      // Semester 5 Civil subjects
      'Design of Reinforced Concrete Structures-I',
      'Concrete Lab',
      'Highway Engineering',
      'Highway Engineering Lab',
      'Geotechnical Engineering-I',
      'Geotechnical Lab-I',
      'Water Resources Engineering',
      'Quantity Surveying and Cost Evaluation',
      'Philosophy for Engineers: Society, Culture and Ethics',
      'Honors Elective-I',
      'Quantity Surveying and Cost Evaluation (Institute Elective-I)',
      'Building Materials and Construction (Institute Elective-II)',
      // Semester 6 Civil subjects
      'Design of Steel Structures',
      'Traffic Engineering',
      'Traffic Engineering Lab.',
      'Geotechnical Engineering-II',
      'Geotechnical Lab-II',
      'Environmental Engineering-I',
      'Water Quality Lab',
      'Industrial Training and Presentation',
      'Honors Elective-II',
      'Environmental Engineering (Institute Elective-I)',
      'Civil Engineering Drawing (Institute Elective-II)',
      // Semester 7 Civil subjects
      'Pre-Project work',
      'Honours Elective-III',
      'Honours Elective-IV',
      'Honours Elective-V',
      // Semester 3 Electrical subjects
      'Electric Circuit Analysis',
      'Electric Machines I',
      'Electromagnetic Field & Waves',
      'Electric Circuit Analysis Lab',
      'Python Programming Lab',
      // Semester 4 Electrical subjects
      'Electrical Measurements and Instrumentation',
      'Electric Machines II',
      'Power Systems I',
      'Control Systems I',
      'Basic Management Principles',
      'Electric Machines Lab I',
      'Control Systems LAB',
      'Electrical Measurements and Instrumentation Lab',
      // Semester 5 Electrical subjects
      'Control Systems II',
      'Power Systems II',
      'Power Electronics',
      'Electric Machines III',
      'Program Elective I',
      'Institute Elective I',
      'Power Systems Lab I',
      'Power Electronics Lab',
      'Electric Machines Lab II',
      // Semester 6 Electrical subjects
      'Power Systems III',
      'Electric Drives',
      'Design of Electric Machines',
      'Microprocessors',
      'Program Elective II',
      'Program Elective III',
      'Power Systems Lab II',
      'Microprocessors Lab',
      'Industrial Training & Viva',
      // Semester 7 Electrical subjects
      'Power System Protection',
      'Program Elective IV',
      'Program Elective V',
      'Program Elective VI',
      'Program Elective VII',
      'Program Elective VIII',
      'Personal Financial Planning',
      'Power System Protection Lab',
      'Program Elective Lab I'
    ];

    const cleanSubject = (subject || 'General').trim();
    const isValid = allowedSubjects.some(sub => sub.toLowerCase() === cleanSubject.toLowerCase());
    if (!isValid) {
      return NextResponse.json({ 
        error: `Decorum Guard: Invalid subject "${cleanSubject}". You can only publish materials under the approved course directories.` 
      }, { status: 400 });
    }

    const matchedSubject = allowedSubjects.find(sub => sub.toLowerCase() === cleanSubject.toLowerCase())!;

    await connectToDatabase();

    const newMaterial = await StudyMaterial.create({
      title,
      subject: matchedSubject,
      description,
      branch,
      semester: parseInt(semester),
      type,
      fileUrl,
      author,
      uploaderId: uploaderId || 'public-user',
      downloadCount: 0,
      views: 0,
      status: 'approved'
    });

    return NextResponse.json({ data: newMaterial });
  } catch (error: any) {
    console.error('Failed to create material:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
